### ISSUE TITLE
boot problem

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/enigma2-openpli-rpi#38]
Hi my friends,
I just compiled a new test image and screen after loading enigma2 is green only, is this because of new userland updates or enigma2 changes regarding e2-rpihddevice?

**Comment by milaebrothers** [comment]
Hi to all, I'm very busy in this period, because I'm changing house.
I commented omx calls on volume.cpp, if the problem persist we can comment omx calls in decoder.cpp and at last on enigma2.cpp. I hope to continue this work next yeaar.
